### ISSUE TITLE
urls-darklist.json moved

### ISSUE THREAD

**Issue by scoope3** [Plenglin/ICO-Moderator#1]
Hello,

It appears that the location of urls-darklist.json has moved from the ethereum lists; consequently, link blocker is no longer working. The new url is https://github.com/MyEtherWallet/ethereum-lists/blob/master/urls/urls-darklist.json. Please update.

**Comment by Plenglin** [comment]
The URL was the same. They just changed the format of the file, throwing a wrench in the URL fetching mechanism. The issue has been fixed.
